// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import CopyTextController from "./copy_text_controller"
application.register("copy-text", CopyTextController)

import ExerciseController from "./exercise_controller"
application.register("exercise", ExerciseController)

import GameController from "./game_controller"
application.register("game", GameController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import LobbySubscribeController from "./lobby_subscribe_controller"
application.register("lobby-subscribe", LobbySubscribeController)

import MultiplayerroomSubscriptionController from "./multiplayerroom_subscription_controller"
application.register("multiplayerroom-subscription", MultiplayerroomSubscriptionController)

import TimerController from "./timer_controller"
application.register("timer", TimerController)
